# code: language=ansible

aria2:
  composes:
    - file: docker-compose.yml
      template: "{{ playbook_dir }}/docker-compose.yml.j2"
      vars:
        PROPAGATION_DOWNLOAD: false
        BIND_DOWNLOAD: downloads
    - file: docker-compose@caddy.yml
      src: "{{ inventory_dir }}/../aria2/docker-compose@caddy.yml"
    - file: docker-compose@traefik.yml
      src: "{{ inventory_dir }}/../aria2/docker-compose@traefik.yml"
