# code: language=ansible

frp:
  server:
    composes:
      - file: docker-compose.yml
        template: "{{ playbook_dir }}/docker-compose.yml"
      - file: docker-compose@caddy.yml
        src: "{{ inventory_dir }}/../frp/server/docker-compose@caddy.yml"
      - file: docker-compose@traefik.yml
        src: "{{ inventory_dir }}/../frp/server/docker-compose@traefik.yml"

  client:
    composes:
      - file: docker-compose.yml
        template: "{{ playbook_dir }}/docker-compose.yml"
      - file: docker-compose@caddy.yml
        src: "{{ inventory_dir }}/../frp/client/docker-compose@caddy.yml"
      - file: docker-compose@traefik.yml
        src: "{{ inventory_dir }}/../frp/client/docker-compose@traefik.yml"
