# code: language=ansible

homebridge:
  composes:
    - file: docker-compose.yml
      template: "{{ playbook_dir }}/docker-compose.yml"
    - file: docker-compose@caddy.yml
      src: "{{ inventory_dir }}/../homebridge/docker-compose@caddy.yml"
    - file: docker-compose@traefik.yml
      src: "{{ inventory_dir }}/../homebridge/docker-compose@traefik.yml"
