# code: language=ansible

jenkins:
  envs:
    - file: external_env-all.env
      content: |
        JENKINS_UC=https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates
        JENKINS_UC=https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/dynamic-stable-2.414.3/update-center.actual.json
        JENKINS_UC_EXPERIMENTAL=https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/experimental/update-center.actual.json
        JENKINS_PLUGIN_INFO=https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/current/plugin-versions.json
        JENKINS_UC_DOWNLOAD=https://mirrors.tuna.tsinghua.edu.cn/jenkins
  composes:
    - file: docker-compose.yml
      template: "{{ playbook_dir }}/docker-compose.yml"
    - file: docker-compose@caddy.yml
      src: "{{ inventory_dir }}/../jenkins/docker-compose@caddy.yml"
    - file: docker-compose@traefik.yml
      src: "{{ inventory_dir }}/../jenkins/docker-compose@traefik.yml"

  plugin:
    delegate_to: localhost
    
    # use jenkins-plugin-cli
    mode: cli
    docker_image: jenkins/jenkins:2.414.3-jdk17
    
    # use jenkins-plugin-manager
    # mode: manager
    # docker_image: eclipse-temurin:11-jre-jammy
    
    jenkins_version: 2.414.3
    file: "{{ inventory_dir }}/../jenkins/plugins.yml"
    output: "{{ inventory_dir }}/../jenkins/plugin/{{ inventory_hostname }}/"
    flags: "--verbose --latest true"

    container:
      envs:
        # The mirror source does not support url redirection https://updates.jenkins.io/update-center.json?version=2.414.3
        - file: external_env-all.env
          content: |
            JENKINS_UC=https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/dynamic-stable-2.414.3/update-center.actual.json
            JENKINS_UC_EXPERIMENTAL=https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/experimental/update-center.actual.json
            JENKINS_PLUGIN_INFO=https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/current/plugin-versions.json
            JENKINS_UC_DOWNLOAD=https://mirrors.tuna.tsinghua.edu.cn/jenkins
