# code: language=ansible

nexus:
  composes:
    - file: docker-compose.yml
      template: "{{ playbook_dir }}/docker-compose.yml"
    - file: docker-compose@caddy.yml
      src: "{{ inventory_dir }}/../nexus/docker-compose@caddy.yml"
    - file: docker-compose@traefik.yml
      src: "{{ inventory_dir }}/../nexus/docker-compose@traefik.yml"
