# code: language=ansible

zoneminder:
  composes:
    - file: docker-compose.yml
      template: "{{ playbook_dir }}/docker-compose.yml"
    - file: docker-compose@mariadb.yml
      src: "{{ inventory_dir }}/../zoneminder/docker-compose@mariadb.yml"
    - file: docker-compose@caddy.yml
      src: "{{ inventory_dir }}/../zoneminder/docker-compose@caddy.yml"
    - file: docker-compose@traefik.yml
      src: "{{ inventory_dir }}/../zoneminder/docker-compose@traefik.yml"
