version: "3.8"

networks:
  traefik:
    name: traefik_traefik

services:
  transmission:
    networks:
      - traefik
    labels:
      - "traefik.http.routers.transmission.rule=Host(`transmission.local`)"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"
      - "traefik.docker.network=traefik_traefik"
