# code: language=ansible

workspace:
  package:
    - sshpass
    - rsync
    - git
    - jq
    # for esxi-iso.add
    - genisoimage
  pip:
    - jsondiff==2.0.0
    - jmespath==1.0.1
    # bug for https://github.com/yaml/pyyaml/issues/724
    - PyYAML==5.3.1
    - lxml==4.9.2
    # bug for https://github.com/docker/docker-py/issues/3113
    - requests==2.28.1
    # for https://docs.ansible.com/ansible/latest/collections/community/vmware/index.html
    - PyVmomi==8.0.2.0

ssh:
  name: esxi.lan
  group: ssh
  approve_task: "{{ inventory_dir }}/../../../../esxi/seed/seed-ssh.approve.yml"
  known_scan:
    - ssh-rsa
    - ecdsa-sha2-nistp256

system:
  group: none
