version: "3.8"

networks:
  traefik:
    name: traefik_traefik

services:
  homeassistant:
    networks:
      - traefik
    labels:
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.local`)"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.docker.network=traefik_traefik"
