version: "3.8"

networks:
  traefik:
    name: traefik_traefik

services:
  gitlab-ce:
    networks:
      - traefik
    labels:
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.local`)"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_traefik"
