# code: language=ansible

workspace:
  package:
    - sshpass
    - rsync
    - git
    - jq
  pip:
    - jsondiff==2.0.0
    - jmespath==1.0.1
    # bug for https://github.com/yaml/pyyaml/issues/724
    - PyYAML==5.3.1
    - lxml==4.9.2
    # bug for https://github.com/docker/docker-py/issues/3113
    - requests==2.28.1
  local: "{{ inventory_dir }}/../../../../"
  seedpath: .seed

ssh:
  name: dsm.local
  group: ssh
  known_scan:
    - ssh-rsa
    - ssh-ed25519
    - ecdsa-sha2-nistp256

system:
  group: docker
  init_task: "{{ inventory_dir }}/../../../../dsm/seed/seed-docker.init.yml"

docker:
  pip:
    - jsondiff==2.0.0
    - jmespath==1.0.1
    # bug for https://github.com/yaml/pyyaml/issues/724
    - PyYAML==5.3.1
    - lxml==4.9.2
    # bug for https://github.com/docker/docker-py/issues/3113
    - requests==2.28.1
    - docker==6.0.1
    - docker-compose==1.29.2
  pip_index: https://pypi.tuna.tsinghua.edu.cn/simple
  pip_mode: shell
