# code: language=ansible

netsh:
  port_proxy:

  port_range:

  groups:
    - test

netsh_groups:
  test:
    port_proxy:
      v4tov4:
        - protocol: tcp
          listenaddress: 0.0.0.0
          listenport: 8001
          connectaddress: 127.0.0.1
          connectport: 9001
      v4tov6:
        - protocol: tcp
          listenaddress: 0.0.0.0
          listenport: 8002
          connectaddress: ::1
          connectport: 9002
      v6tov4:
        - protocol: tcp
          listenaddress: ::1
          listenport: 8003
          connectaddress: 127.0.0.1
          connectport: 9003
      v6tov6:
        - protocol: tcp
          listenaddress: ::1
          listenport: 8004
          connectaddress: ::1
          connectport: 9004

    port_range:
      dynamic:
        ipv4:
          protocol: tcp
          startport: 49152
          numberofports: 16384
          store: persistent
        ipv6:
          protocol: tcp
          startport: 49152
          numberofports: 16384
          store: persistent
      excluded:
        ipv4:
          - protocol: tcp
            startport: 8000
            numberofports: 2000
            store: persistent
          - protocol: tcp
            startport: 3000
            numberofports: 1
            store: persistent
          - protocol: tcp
            startport: 6000
            numberofports: 1000
            store: persistent
        ipv6:
          - protocol: tcp
            startport: 8000
            numberofports: 2000
            store: persistent
          - protocol: tcp
            startport: 3000
            numberofports: 1
            store: persistent
          - protocol: tcp
            startport: 6000
            numberofports: 1000
            store: persistent
