version: "3.8"

networks:
  caddy:
    name: caddy_caddy

services:
  zoneminder:
    networks:
      - caddy
    labels:
      caddy: zoneminder.local:443, zoneminder.local:80
      caddy.reverse_proxy: "{{ upstreams 80 }}"
