version: "3.8"

networks:
  caddy:
    name: caddy_caddy

services:
  qinglong:
    networks:
      - caddy
    labels:
      caddy: qinglong.local, qinglong.local:80
      caddy.reverse_proxy: "{{ upstreams 5700 }}"
