version: "3.8"

networks:
  caddy:
    name: caddy_caddy

services:
  dupeguru:
    networks:
      - caddy
    labels:
      caddy: dupeguru.local, dupeguru.local:80
      caddy.reverse_proxy: "{{ upstreams 5800 }}"
