version: "3.8"

networks:
  caddy:
    name: caddy_caddy

services:
  domoticz:
    networks:
      - caddy
    labels:
      caddy: domoticz.local, domoticz.local:80
      caddy.reverse_proxy: "{{ upstreams 8080 }}"
