version: "3.8"

networks:
  caddy:
    name: caddy_caddy

services:
  xui:
    networks:
      - caddy
    labels:
      caddy: xui.local, xui.local:80
      caddy.reverse_proxy: "{{ upstreams 54321 }}"
