version: "3.8"

networks:
  traefik:
    name: traefik_traefik

services:
  grafana:
    networks:
      - traefik
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.local`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_traefik"
