# code: language=ansible

workspace:
  package:
    - sshpass
    - rsync
    - git
    - jq
  pip:
    - jsondiff==2.0.0
    - jmespath==1.0.1
    # bug for https://github.com/yaml/pyyaml/issues/724
    - PyYAML==5.3.1
    - lxml==4.9.2
    # bug for https://github.com/docker/docker-py/issues/3113
    - requests==2.28.1

ssh:
  name: openwrt.local
  group: ssh
  approve_task: "{{ inventory_dir }}/../../../../openwrt/seed/seed-ssh.approve.yml"

system:
  group: python
  init_task: "{{ inventory_dir }}/../../../../openwrt/seed/seed-python.init.yml"

python:
  opkg:
    - sudo
    - python3
    - python3-pip
  # pip: []
  # opkg_host: mirrors.cloud.tencent.com
  # pip_index: https://pypi.tuna.tsinghua.edu.cn/simple

