version: "3.8"

networks:
  traefik:
    name: traefik_traefik

services:
  subconverter:
    networks:
      - traefik
    labels:
      - "traefik.http.routers.subconverter.rule=Host(`subconverter.local`)"
      - "traefik.http.services.subconverter.loadbalancer.server.port=25500"
      - "traefik.docker.network=traefik_traefik"

  subweb:
    networks:
      - traefik
    labels:
      - "traefik.http.routers.subweb.rule=Host(`subweb.local`)"
      - "traefik.http.services.subweb.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_traefik"
