version: "3.8"

networks:
  caddy:
    name: caddy_caddy

services:
  subconverter:
    networks:
      - caddy
    labels:
      caddy: subconverter.local, subconverter.local:80
      caddy.reverse_proxy: "{{ upstreams 25500 }}"

  subweb:
    networks:
      - caddy
    labels:
      caddy: subweb.local, subweb.local:80
      caddy.reverse_proxy: "{{ upstreams 80 }}"
