# code: language=ansible

vm:
  groups:
    - free_iso_guest
    - free_vmdk_guest
    - vcsa_iso_guest
    - vcsa_vmdk_guest
    - vcsa_vmdk_ovf

vm_groups:

  # free esxi server iso from url
  free_iso_guest:
    file:
      # cloudinit verion 23.2.1
      # iso cant support vmware datasource esxifree_guest `cloudinit_userdata` not work
      - path: /vmfs/volumes/datastore1/ubuntu-22.04.3-live-server-amd64.iso
        src: /$HOME/.esxi/ubuntu-22.04.3-live-server-amd64.iso
        url: https://releases.ubuntu.com/jammy/ubuntu-22.04.3-live-server-amd64.iso
    guest:
      name: "ubuntu-server-22"
      guest_id: ubuntu-64
      hardware:
        version: 15
        num_cpus: 2
        memory_mb: 2048
      disks:
        - size_gb: 10
          type: "thin"
          volname: "thin"
          boot: true
      cdrom:
        # NOT support multiple iso
        type: "iso"
        iso_path: "/vmfs/volumes/datastore1/ubuntu-22.04.3-live-server-amd64.iso"
      networks:
        - networkName: VM Network
          virtualDev: vmxnet3

  # free esxi server vmdk from local file
  free_vmdk_guest:
    file:
      - path: /vmfs/volumes/datastore1/jammy-server-cloudimg-amd64.vmdk
        src: /$HOME/.esxi/jammy-server-cloudimg-amd64.vmdk
        url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.vmdk"
        # clone by esxifree_guest
        # vmkfstools:
        #   path: /vmfs/volumes/datastore1/jammy-server-cloudimg-amd64.vmdk
        #   clone:
        #     format: thin
    guest:
      name: "ubuntu-server-jammy"
      hardware:
        version: 15
        num_cpus: 1
        memory_mb: 384
      disks:
        # NOT support use `boot` and `src` same time, so it must be removed manually
        - size_gb: 1
          type: "thin"
          volname: "boot"
          boot: true
        - size_gb: 10
          type: "thin"
          volname: "cloudimg"
          src:
            backing_filename: "[datastore1] /jammy-server-cloudimg-amd64.vmdk"
            copy_or_move: "copy"
      networks:
        - networkName: VM Network
          virtualDev: vmxnet3
          cloudinit_netplan:
            version: 2
            ethernets:
              ens192:
                addresses:
                  - 192.168.1.201/25
                dhcp4: false
                gateway4: 192.168.1.1
                nameservers:
                  addresses:
                    - 192.168.1.2
                    - 8.8.8.8
                    - 8.8.4.4
                  search:
                    - local.dougalseeley.com
      cloudinit_userdata:
        #cloud-config
        runcmd:
          - echo 'cloud-init vmware datasource initialization completed!' > /var/tmp/cloud-init-cmd.txt

        users:
          - default

        system_info:
          default_user:
            name: ubuntu
            plain_text_passwd: 'ubuntu'
            home: /home/ubuntu
            shell: /bin/bash
            lock_passwd: false
            gecos: Ubuntu
            groups: [adm, cdrom, dip, lxd, sudo]
      wait: false

  # vcsa esxi server iso from url and make cloudinit iso for init
  vcsa_iso_guest:
    file:
      - path: /vmfs/volumes/datastore1/ubuntu-20.04.6-live-server-amd64.iso
        src: $HOME/.esxi/ubuntu-20.04.6-live-server-amd64.iso
        url: https://releases.ubuntu.com/focal/ubuntu-20.04.6-live-server-amd64.iso
      # make cloudinit iso
      - path: /vmfs/volumes/datastore1/ubuntu-cloudinit.iso
        src: $HOME/.esxi/ubuntu-cloudinit.iso
        cloudinit:
          meta_data: |
            instance-id: cloud-host-0
            local-hostname: cloudhost
          user_data:
            #cloud-config
            runcmd:
              - echo 'Hello, World!' > /var/tmp/hello-world.txt

            autoinstall:
              version: 1
              locale: en_US.UTF-8
              keyboard:
                layout: us
              storage:
                layout:
                  name: lvm
              identity:
                hostname: ubuntu-server
                username: ubuntu
                password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
              ssh:
                install-server: yes
                allow-pw: yes
    guest:
      name: "ubuntu-server-20"
      guest_id: ubuntu64Guest
      datastore: DATA
      hardware:
        boot_firmware: efi
        num_cpus: 2
        memory_mb: 2048
        scsi: paravirtual
      disks:
        - size: 500gb
          type: thin
          datastore: DATA
      cdrom:
        - controller_type: ide
          controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: "[datastore1] ubuntu-20.04.6-live-server-amd64.iso"
        - controller_type: ide
          controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: "[datastore1] ubuntu-cloudinit.iso"
      networks:
        - name: "Internal"
          device_type: vmxnet3
          connected: true
          start_connected: true
          ip: 192.168.1.210
          netmask: 255.255.255.0
          gateway: 192.168.1.1
      customization:
        dns_servers:
          - 8.8.8.8

  # vcsa esxi server vmdk from local file
  vcsa_vmdk_guest:
    file:
      # vmkfstools extend vmdk
      - path: /vmfs/volumes/datastore1/openwrt-vmdk-22/openwrt-vmdk-22.vmdk
        src: /$HOME/.esxi/openwrt-22.03.5-x86-64-generic-squashfs-combined-efi.vmdk
        vmkfstools:
          path: /vmfs/volumes/datastore1/openwrt-22.03.5-x86-64-generic-squashfs-combined-efi.vmdk
          clone:
            format: thin
    guest:
      name: "openwrt-vmdk-22"
      hardware:
        version: 15
        num_cpus: 1
        memory_mb: 384
      disks:
        - size: 500gb
          type: thin
          datastore: DATA
          filename: "[datastore1] openwrt-vmdk-22/openwrt-vmdk-22.vmdk"
      networks:
        - networkName: VM Network
          virtualDev: vmxnet3

  # vcsa esxi server ovf from local file
  vcsa_vmdk_ovf:
    file:
      - path: /vmfs/volumes/datastore1/openwrt-22.03.5-x86-64-generic-squashfs-combined-efi.ovf
        src: /$HOME/.esxi/openwrt-22.03.5-x86-64-generic-squashfs-combined-efi.ovf
    ovf:
      datacenter: Datacenter1
      esxi_hostname: "{{ vmware.hostname }}"
      name: "openwrt-ovf-22"
      datastore: datastore1
      ovf: openwrt-22.03.5-x86-64-generic-squashfs-combined-efi.ovf
      networks:
        - networkName: VM Network
          virtualDev: vmxnet3
      power_on: false
