#!/usr/bin/env -S ansible-galaxy install -r

roles:
  - name: stephdewit.nvm

  - name: comcast.sdkman

  - name: stefangweichinger.ansible_rclone

collections:

  - name: community.general

  - name: community.docker
