version: "3.8"

networks:
  traefik:
    name: traefik_traefik

services:
  headscale-ui:
    networks:
      - traefik
    labels:
      - "traefik.http.routers.headscale-ui.rule=Host(`headscale-ui.local`)"
      - "traefik.http.services.headscale-ui.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_traefik"
