version: "3.8"

networks:
  caddy:
    name: caddy_caddy

services:
  headscale-ui:
    networks:
      - caddy
    labels:
      caddy: ui.headscale.local, ui.headscale.local:80
      caddy.reverse_proxy: "{{ upstreams 80 }}"
