version: "3.8"

networks:
  traefik:
    name: traefik_traefik

services:
  syncthing:
    networks:
      - traefik
    labels:
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.local`)"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.docker.network=traefik_traefik"
