version: "3.8"

networks:
  caddy:
    name: caddy_caddy

services:
  homebridge:
    networks:
      - caddy
    labels:
      caddy: homebridge.local, homebridge.local:80
      caddy.reverse_proxy: "{{ upstreams 8581 }}"
